# Bienestar Social

En el presente apartado se presentan el marco metodológico de Bienestar Social desarrollado por la OCDE en los informes de Calidad de Vida, además de detallar su reciente implementación en Chile a partir de la Encuesta de Bienestar Social (EBS) la cual se realiza como un anexo a la encuesta CASEN de Pandemia. Destaca de este último los indicadores seleccionados y la decisión de no medir sustentabilidad en la encuesta.

Esta mirada del bienestar es complementaria al análisis de pobreza. Esta última se destaca por definir carencias y umbrales aceptables de estas, cosa de identificar aquellas personas y hogares cuya situación es precaria. En cambio, el enfoque de bienestar social está fuertemente influenciado por las capacidades de Sen y por cuantificar las distintas expresiones de logros que las personas tienen en la sociedad. Es así que incorpora elementos objetivos y subjetivos, además de conexión y participación social, con elementos de bienestar material y salud.

Las ideas principales de estos desarrollos se relacionan con:

- Limitantes del PIB como indicador de progreso social

- Enfoque de Capacidades de Amartya Sen

- Preocupación por la Sustentabilidad del Bienestar

Este enfoque metodológico es interesante por presentar una visión validada internacionalmente y por más de 10 años de trabajo de parte de los informes publicados por OECD. Presenta un esfuerzo por consolidar visiones y ampliar la visión y las medidas para cuantificar el bienestar de la población. 

La disponibilidad de la Encuesta a representatividad Regional presenta interesantes oportunidades de investigación, vinculación de datos, uso de técnicas de estimación de área pequeña y la posibilidad de "calibrar" modelos comparando otros enfoques de análisis del bienestar.

## Motivación

### Limitantes del PIB

Las críticas a las limitantes del PIB como indicador de bienestar son tan antiguas como su uso. Este siempre se ha entendido como una visión parcial basada en la producción de bienes y servicios, sin embargo al ser medido consistentemente permite una facil comparación y evaluación de las trayectorias de los países.

A partir de la Comsión Sarkozy (2009) que se han trabajado y generado esfuerzos por ampliar los marcos estadísticos para medir de mejor manera el bienestar.

Entre las críticas enunciadas por la OCDE en su infor How's Life se menciona:

- No buena medida de ingreso de residentes, al incluir pagos a no residentes y excluir ingresos de residentes por pagos en otros países

- Sobre estimación de producción para consumo (bienes de capital)

- No informa cómo comparten recursos los individuos

- No mide factores de servicio hogareños producidos por el hogar como el cuidado de niños y crianza

- Algunes elementso que aumentan el PIB son reduccion de bienestar (costos de congestión, mayor tiempo de traslado) o actividades destinadas a remediar costos sociales y ambientales de produccion

- Atributos claves de bienestar de individuos y comunidades no son capturados por el sistema de cuentas nacionales (estado de salud, felicidad, seguridad, conexiones sociales

- No puede mostrar si el bienestar puede sustentarse en el tiempo, ya que solo integra parcialmente información de tipos de capital que sostienen el bienestar.

### Enfoque Capacidades

Medir el bienestar es desafiante por la necesidad de revisar e integrar distintos aspectos de la vida de las personas y su importancia relativa. Es un fenómeno complejo, donde muchos de sus determinantes se correlacionan entre sí, por lo que se necesita un marco de trabajo.

La medición del bienestar se relaciona a los trabajos de Sen en sentido de que se basa en la condicion de la persona, buscando ampliar sus capacidades y opciones de las personas y comunidades. Conceptos claves serían los "resultados" o "funcionamientos logrados" que son estados o actividades que las personas alcanzan o realizan, y "oportunidades" que son las capacidades y medios que bsan lo que las personas pueden lograr. 

Es así que se recalca la importancia de las libertades y las oportunidades que la sociedad genera y entrega a las personas.

## Marco Teórico del Bienestar

Con el objetivo de guiar la medición, se propone un marco teórico que considera tres pilares para el bienestar: Las condiciones materiales de vida, la calidad de vida y la sustentabilidad.

Con esto se busca distinguir entre el bienestar hoy y mañana, siendo las condiciones materiales importantes para el primero, y para el segundo las condiciones para preservar este bienestar.

El foco se centra en Hogares o Individuos (en vez de agregar condiciones para la economia nacional), Resultados de Bienestar (en vez de variables de inputs o output; estado de salud más que atenciones médicas), Distribución del bienestar entre individuos (grupos de edad, género, ingreso o socioeconómico), Aspectos Objtivos y Subjetivos del Bienestar (aspecto psicológicos de los haceres y seres de las personas).

Es así que el pilar de condiciones materiales se enfoca en aspectos que afectan el bienestar hoy como los ingresos, la vivienda y el trabajo. El pilar de calidad de vida mide de manera más completa la salud, educacion, conexiones sociales, ambiente, seguridad, etc. Mientras que la Sustentabilidad se expresa en el pilar que mide capital natural, economico, humano y social.

Es importante revisar así las relaciones entre las dimensiones, considerando que existen patrones no sustentables posibles, donde el bienestar hoy puede estar en peligro de ser mantenido por consumo excesivo o depredasión natural o falta de inversión en capital necesario para el bienestar.

### Dimensiones

Las dimensiones propouestas por este marco teórico se agrupan en los tres pilares mencionados

#### Condiciones Materiales de Vida

- Ingresos y Riqueza: posibilidades de consumo.

- Trabajos e Ingresos: Disponibilidad implica recursos y bienestar.

- Vivienda: Necesidades básicas, seguridad personal, privacidad y espacio personal.


#### Calidad de Vida

- Estado de Salud: permite realizar actividades (incluído trabajar).

- Balance trabajo y vida: poder dedicarle tiempo a actividades no remuneradas permite a las personas mantenerse saludables y productivas.
- Educación y Habilidades: es un gran activo y mejora el estándar de vida de individuos y de la sociedad.

- Conexiones Sociales: necesidad básica, además ayuda a lograr otros objetivos importantes, como encontrar trabajo.

- Gobernanza e involucramiento cívico: permite a las personas tener mayor control de sus vidas.

- Calidad Ambiental: afecta la salud y posibilidad de las personas de realizar un conjunto de actividades.

- Seguridad Personal: afecta la salud y posibilidad de las personas de realizar un conjunto de actividades

- Bienestar Subjetivo: importante para evaluar si las personas están satisfechas con sus vidas como un todo, y si esto es resultado de circunstancias objetivas u otros factores.

#### Sustentabilidad del Bienestar en el Tiempo

La medición de la sustentabilidad del bienestar se enfoca en revisar la evolución en el tiempo de diferentes stocks de capital (Económico, Ambiental, Humano y Social) los cuales sostienen las varias dimensiones del bienestar. Además de analizar las decisiones que afectan a estos stocks. 

- Capital Natural.

- Capital Económico.

- Capital Humano.

- Capital Social.

Patrones no sustentables de desarrollo pueden reflejar consumos excesivos de recursos de hoy e inversiones inadecuadas, o desbalances en la composición de los variados stocks. Esto implica revisar las condiciones de los sistemas (económicos, social y ecológico) de los cuales son parte los individuos.

## Encuesta Bienestar Social

La Encuesta de Bienestar Social (EBS) adapta el marco teórico a Chile. Se realizan algunos ajustes para este fin, donde se destacan los conceptos de "Oportunidades" y "Resultados" dentro de cada dimensión. Además, se relaciona más explicitamente el enfoque con los objetivos de desarrollo sostenible (ODS) y un enfoque de Derechos Humanos y de Género más explícito. 

En términos específicos, algunos ajustes realizados:

- En la dimension de Ingresos, se mide la suficiencia de estos y la seguridad financiera.

- En empleo, medir aspectos cualitativos asociados a la valoración de trabajadores.

- En vivienda, medir calidad, sensación térmica y calidad del entorno.

- En salud, concentrarse en oportunidades de acceder a prestaciones y medicamentos de forma oportuna.

Ademáse se considera la Estado como un agente movilizador.

Finalmente se omite la medición de sustentabilidad considerando que la medición de los stocks de capital relacionados se relacioinan más a otras instituciones (como el Banco Central entre otras)

### Dimensiones

#### Condiciones Materiales

##### Dimensión Ingresos: 
Busca evaluar si las personas gozan y disponen de oportunidades que les brinden seguridad económica

- Resultados: gozar de seguridad económica.

    - Tasa de pobreza por ingresos.
    
    - Ingreso del Hogar.
    
    - Desigualdad GINI.
    
    - Suficiencia de Ingresos.
    
    - Cobertura del endeudamiento.
    
- Oportunidades: disponer de oportunidades para gozar de seguridad económica.

    - Capacidad para cubrir cuentas básicas.
    
    - Estrategias ante shocks de ingresos.
    
##### Dimensión Trabajo: 

Busca evaluar si las personas cuentan y disponen de oportunidades para un empleo que les permita el desarrollo personal.

- Resultados: contar con un empleo que permita el desarrollo personal.

    - Situación de Ocupación.
    
    - Situación de desempleo de largo plazo.
    
    - Situación Contractual.
    
    - Jornada.
    
    - Valoración de los aspectos de calidad del empleo.
    
    - Percepción de empleabilidad.
    
- Oportunidades:

    - Capacidades habilitadas por el empleo.

##### Dimensión Vivienda: 

Busca evaluar si las personas disponen de una vivienda en buenas condiciones, así como si disponen de acceso a equipamiento básico del hogar y servicios básicos del entorno.

- Resultados: disponer de una vivienda en buenas condiciones.

    - Tipo y tenencia de la vivienda.
    
    - Tasa de hacinamiento.
    
    - Materialidad y estado de conservación.
    
    - Problemas de calidad de la vivienda.
    
    - Sensación de confort térmico.
    
- Oportunidades: acceso a servicios básicos para la vivienda y el entorno.

    - Acceso a instalaciones sanitarias básicas.
    
    - Acceso a internet.
    
    - Acceso a combustibles para calefacción,
    
    - Acceso a servicios básicos
    

#### Calidad de Vida

##### Dimensión Salud: 

Evaluar si las personas gozan y tienen oportunidades para disponer de buena salud.

- Resultados: Gozar de buena salud.

    - Prestaciones de salud.
    
    - Dificultades en la vida diaria.
    
    - Dependencia.
    
    - Auto reporte de estado de salud.
    
    - Sobrepeso y obesidad.
    
    - Estado de salud mental: ansiedad y depresión (PHQ4).
    
- Oportunidades:

    - Inseguridad alimentaria.
    
    - Capacidades habilitadas por el estado de salud.
    
    - Acceso a atenciones de salud.
    
    - Acceso a medicamentos.
    
    - Percepción de inseguridad financiera.
    
##### Dimensión Balance Vida y Trabajo: 

Evaluar si las personas logran conciliar el uso del tiempo y disponen de autonomía para decidir sobre el uso del tiempo en su vida cotidiana 

- Resultados: Conciliar el uso del tiempo en la vida cotidiana.

    - Distribución del tiempo en la vida cotidiana.
    
    - Satisfacción con la distribución del tiempo en la vida cotidiana.
    
    - Dobre presencia.
    
- Oportunidades: Autonomía para decidir sobre el uso del tiempo en la vida cotidiana.

    - Flexibilidad en el trabajo para balancear trabajo y familia.
    
    - Acceso a cuidado NNA (Estado, mercado empleador, familia y amigos).
    
##### Dimensión Educación: 

Evaluar si las personas tienen educación y si disponen de oportunidades para educarse.

- Resultados: Ser educado.

    - Nivel educacional.
    
    - Interés en seguir estudiando.
    
- Oportunidades: 

    - Capacidades habilitadas por el nivel educacional.
    
    - Posibilidad de educarse.
    
    - Barreras para continuar estudiando.
    
##### Dimensión Relaciones Sociales: 

Evaluar si las personas son parte y tienen oportunidades para establecer relaciones sociales, y si disponen de confianza en la posición que ocupan en la sociedad.

- Resultados: Ser parte de relaciones sociales y tener confianza en la posición que se ocupa en la sociedad.

    - Tamaño y calidad de la red.
    
    - Confianza en otros.
    
    - Experiencia de malos tratos.
    
    - Lugar de experiencia de malos tratos.
    
    - Razón de malos tratos.
    
- Oportunidades: Oportunidades para establecer relaciones sociales, ser reconocido y respetado en la sociedad.
    
    - Heterogeneidad de la red.
    
    - Soporte de redes sociales.
    
##### Dimensión Compromiso Cívico y Gobernanza: 

Evaluar si las personas participan políticamente, confían en las instituciones y tienen las oportunidades para incidir en decisiones comunitarias

- Resultados: Participación política y confianza en las instituciones.

    - Confianza en las instituciones.
    
    - Participación social.
    
    - Participación en acciones políticas.
    
- Oportunidades: Oportunidades de participación y para incidir en decisiones comunitarias.

    - Barreras para participar en organizaciones.
    
    - Nivel de participación en las decisiones de la comunidad/país.
    
##### Dimensión Calidad Medioambiental: 

Evaluar si las personas disfrutan y tienen oportunidades para gozar de un entorno libre de contaminación ambiental.

- Resultados: Gozar de un entorno libre de contaminación ambiental.

    - Frecuencia de acceso a áreas verdes.
    
    - Evaluación de la calidad ambiental de la comunidad o localidad.
    
    - Exposición a problemas ambientales en la vida diaria.
    
- Oportunidades: 

    - Capacidades limitadas por la calidad del medio ambiente
    
##### Dimensión Seguridad Física: 

Evaluar si las personas viven y tienen oportunidades para vivir en un entorno seguro para el desarrollo de las actividades diarias.

- Resultados: 

    - Victimización auto reportada por robos y asaltos.
    
    - Riesgo de sufrir acoso sexual callejero.
    
    - Percepción de Seguridad.
    
- Oportunidades:

    - Entorno inseguro.
    
    - Capacidades limitadas por la seguridad.
    
    - Acceso a mecanismos sociales de protección y seguridad.
    
##### Dimensión Bienestar Subjetivo: 

Evaluar si las personas gozan de una evaluación positiva respecto a sus propias vidas, disponer del balance emocional que experimentan en un momento del tiempo.

- Resultados:

    - Satisfacción de la vida en general
    
    - Balance emocional o afetivo
    
    - Emociones positivas
    
    - Emociones negativas
    
    - Satisfacción de la vida por área
    
