# Pobreza Monetaria

Para caracterizar el bienestar y las carencias de la población y así guiar y evaluar el desarrollo de políticas públicas se recurre al análisis de la pobreza. Con este análisis se busca capturar la capacidad o falta de capacidades que tienen las personas de desarrollarse e integrarse dentro de la sociedad. 

Tradicionalmente en Chile se ha medido a partir del ingreso total per cápita de los hogares, lo que fue actualizado el año 2013.  

Sin embargo se reconoce que la pobreza es un fenómeno más complejo que la falta de ingresos para adquirir una canasta básica de consumo, y que se expresa en un conjunto de carencias en distintas dimensiones. Esto último motivó el desarrollo de la metodología de Pobreza Multidimensional, revisada en detalle en otro apartado.

## Análisis de Pobreza

El análisis de la pobreza implica en general lograr *Identificar* a los hogares y las personas que se encuentran en situación de carencias y luego *Agregar* de manera consistente para caracterizar a la población general.

Este proceso de identificación implica definir un **umbral mínimo** bajo el cual la persona se encuentra en situación de pobreza. Es así que el análisis implica un elemento normativo, al definir la llamada **línea de pobreza**. Esta definición impacta directamente luego la agregación y con esto cómo se caracteriza la evolución del indicador en el territorio.

La idea sería entonces que esta definición de umbral mínimo logre capturar adecuadamente el poder contar con recursos suficientes para desarrollarse e insertarse dentro de la sociedad en al cual se participa. Es decir, el metodo de analisis de la pobreza a partir de ingresos considera el ingreso como un indicador de nivel de vida o de capacidad de satisfacción de necesidades básicas.

### Metodología Tradicional: por Ingresos

La metodología usada desde los años 80 hasta el 2013 es una metodología basada en ingresos, y considera tanto la pobreza como la pobreza extrema o indigencia. [@ministeriodedesarrollosocialNuevaMetodologiaMedicion2015]

Para la pobreza extrema se considera una Canasta Básica de necesidades Alimentarias (CBA) la cual permite identificar si los ingresos percapita del hogar logran financiar el valor de esta canasta, lo que equivale a tener ingresos suficientes para alimentarse. Por otro lado, se considera una canasta ampliada de necesidades alimentarias y no alimentarias para identificar si el hogar está en situación de pobreza. Con esto la linea de pobreza extrema es la CBA y la linea de pobreza es la Canasta Alimentaria y No Alimentaria.

Los patrones de consumo de los hogares son registrado en la Encuesta de Presupuestos Familiares, del INE, con esto, se diferencia entre la canasta de zonas urbanes y rurales. Principalmente porque en las zonas rurales el autoconsumo es mayor.

La medición de los ingresos se realiza mediante la encuesta CASEN.

### Actualización de Metodología de medición de la pobreza.

Durante el año 2013 se realizó una actualización de la medición que considera 

Esta implica cambiar el cálculo de la linea de pobreza del hogar, que en inicia correspende al costo de la canasta básica por el número de integrantes dividido por la proporción de consumo de alimentos en el consumo total. La innovación considera escalas de equivalencia en el consumo del hogar, con lo que al aumentar el numero de integrantes del hogar, la linea de pobreza aumenta menos que proporcionalmente (el gasto aumenta menos que proporcionalmente). Con esto se considera una "linea de pobreza por persona equivalente". Mientras que la linea de pobreza extrema corresponde a 2/3 de la linea de pobreza por persona equivalente.

Esta modificación considera la ocurrencia de economías de escala en el consumo de bienes dentro del hogar, lo que ocurre cuando existen bienes compartidos, como por ejemplo la calefacción. Se usa un parametro de escala de equivalencia uniparametrica, que va entre 0 y 1, para elevar el tamaño del hogar. Donde 0 corresponde a economias de escala absolutas y 1 un bienestar que es el ingreso per capita. El parametro usado en Chile es 0,7.

### Canasta Básica de Alimentos

La canasta básica de alimentos es el conjunto de bienes que en conjunto generan la linea de pobreza. En el país se consudera un umbral de 2000 calorias promedio por persona. Su construcción se realiza en base a la información recopilada por la Encuesta de Presupuestos Familiares del INE.

Además su composición fue determinada a partir del gasto del grupo de la población correspondiente al quintil de hogares de menores ingresos, este se denomina el grupo de referencia.

Para estimar el consumo calórico se usan datos de precios usadas en el cálculo del IPC y mediante una estimación indirecta, de acuerdo a los presupuestos y gastos de los hogares, se calcula el consumo calórico del grupo de referencia y su composición. El detalle de este proceso se puede encontrar en [@ministeriodedesarrollosocialNuevaMetodologiaMedicion2015]

### Ingresos

Para caracterizar los ingresos de las personas y los hogares se utilizan los datos levantados por la encuesta CASEN. En particular se busca medir el **ingreso corriente**, el cual está compuesto por: 

- Ingresos primarios: provenientes del trabajo y de la propiedad de activos

- Transferencias corrientes: Prestaciones de seguros sociales y asistencia social

- Diversas transferencias correintes entre los hogares.

Este ingreso por hogar se transforma luego a persona equivalente para ser calculado con la linea de pobreza para identificar la situación de pobreza del hogar.

El ingreso considerado es entonces el ingreso corriente que se define como la suma del *ingreso autónomo del hogar* (sueldos y salarios, monetarios y en especies, ganancias por trabajo independiente, auto provisión de bienes, rentas, intereses, dividendos y utilidades, jubilaciones, pensiones, transferencias corrientes) y las *transferencias monetarias* que recibe el hogarl del Estado (aportes en dinero por programas sociales), además de una *imputación por concepto de arriendo de la vivienda* cuando esta es habitada por sus propietarios.

Se realiza también un proceso de **imputación de datos faltantes de ingresos** esto debido a los errores de respuesta en las encuestas de hogares, por sub o sobre declaración. A raiz de esto se realiza imputación de datos en aquellas personas o hogares que debiendo reportar ingreso no lo hicieron, a partir de personas u hogares de similares caracteristicas en la encuesta. El detalle de este proceso se encuentra en [@ministeriodedesarrollosocialNuevaMetodologiaMedicion2015]

Finalmente, en esta actualización de la metodología se eliminó el ajuste de los ingresos a cuentas nacionales.

## Vulnerabilidad

Se puede entender la vulnerabilidad como el riesgo de caer en situación de pobreza. Esto implica considerar la pobreza como un fenómeno estocástico. 

Con esto se busca identificar hogares que de ocurrir algún shock de salud o gastos inesperados su situación pase a ser de pobreza.[@chaudhuri2003assessing]

Una manera simple de analizar esto sería ampliar con una banda superior la linea de pobreza, ya que los hogares con ingresos levemente por sobre la linea de pobreza estarían en mayor riesgo. Otros enfoques buscan estimar el ingreso futuro [ @kamanouMeasuringVulnerabilityPoverty2002]

De todas formas el riesgo de caer en pobreza es también un elemento relevante para analizar el bienestar de las personas, ya que puede generar malestar y disminuir la seguridad hacia el futuro y expectativas de los hogares en situación de vulnerabilidad.

## Datos y Representatividad

El análisis de la pobreza en Chile se realiza en base a los datos de la Encuesta de Caracterización Socioeconómica (CASEN) realizada por el Ministerio de Desarrollo Social y Familia (y antes por MIDEPLAN).

La representatividad de esta encuesta es nacional, territorial (urbano y rural) y regional. En general la representividad comunal cambia por los años de realización dependiendo de si es un objetivo del diseño muestral lograr este nivel de representavidad, siendo al comienzo representativa para algunas comunas (autocontenidas) y en las ultimas ediciones incluído un factor de expansión comunal el cual permite realizar análisis comunales sujeto a evaluar la confiabilidad de los resultados.

### SAE Comunal

Los datos de pobreza comunal se derivan de técnicas de estimación de area pequeña (SAE por sus siglas en inglés).

En general se usan modelos de Area que búscan incorporar información adicional, generalmente registros administrativos, para disminuir la varianza de la estimación en unidades territoriales con pocas unidades de muestreo. Además de la imputación por conglomerados para zonas donde no se cuentan con datos (comunas no incluidas en el diseño muestral, por ser zonas de dificil acceso)