# Movilidad Intergeneracional

La movilidad intergeneracional busca analizar qué tan determinantes son los ingresos de los padres en los ingresos de los hijos. Es decir una manera de analizar en qué medida "la cuna manda tu destino". Esto se relaciona con conceptos como las oportunidades de desarrollo, con el rol del capital humano, con la persistencia de privilegios y carencias en la población.

En este apartado se revisan a grandes razgos los elementos destacables de esta literatura, sobretodo relacionado con la posibilidad de desagregar territorialmente estas mediciones, a partir de las publicaciones recientes que analizan el fenómeno en Chile a escala regional y comunal [@cortes-orihuelaDecentralizingChileanMiracle2022; @cortesorihuelaIntergenerationalEarningsPersistence2023] 

## Aspectos Teóricos

Los trabajos conceptuales y empíricos en esta literatura se relacionan con temáticas de educación, capital humano y estructura social. 

La Movilidad Intergeneracional fue formalizada inicialmente por @beckerEquilibriumTheoryDistribution1979 como el grado en que los recursos familiares se transfieren de padres a hijos. Luego @beckerHumanCapitalRise1986 y @solonChapter29Intergenerational1999 mejoran el modelo distinguiendo entre capital humano e ingresos por otras fuentes de riqueza. Modelos más actuales incorporan el rol de la productividad de la inversión en capital humano, la heredabilidad de los privilegios, buscando explicar la alta persistencia en el tope de la distribución [@beckerTheoryIntergenerationalMobility2018] encontrando que los padres de mayores ingresos invierten más en el capital humano de sus hijos, además de generaciónes sucesivas de "familias de clase alta" no necesariamente regrean a la emedia poblacion, desarrollando una especie de "elite de capital humano".

## Formas de Medición y Desafíos

Como se mencionó el concepto general se relaciona con la *persistencia* y la *heredabilidad* de los ingresos. Existen distintas mneras de operacionalizar esto:

- Persistencia de ingresos: En general se mide mediante una regresión lineal entre el logaritmo del ingreso permamente de los hijos y el logaritmo del ingreso permanente de los padres. Una alternativa a esto es usar el ranking en la distribución en vez del logaritmo. El coeficiente entrega una medida de asociación entre los ingresos.

Otras medidas de interés son las *probrabilidades de transición* las cuales analizan las probabilidades condicionales de mantenerse o cambiar de quintil de ingresos. En particular interesa el círculo de pobreza o $p_{11}$, el círculo de privilegio ($p_{55}$) y la probabilidad de llegar al quintil más alto cuando los padres son del quintil más bajo ($p_{15}$).

Para evaluar esto se necesitan datos detallados de los ingresos de las personas y sus familias en el tiempo. Idealmente contar con una muestra de ingresos de ambas generaciones a lo largo de su vida laboral, entre los 25 y los 55 años. Esto para calcular el ingreso permanente de cada persona. En general no se cuenta con esta información pero sí con variables proxies, además es común encontrar métodos de imputación de ingresos en esta literatura. 

Es así que en la práctica pueden ocurrir problemas en la estimación debido a: uso de varaibles inadecuadas como proxies de ingresos permantentes, sesgos de atenuación debido a varianza creciente de ingresos permanentes de hijos, información homogénea por datos sin muestreo aleatoria, y datos incompletos.

## Datos para Chile

A nivel agregado, Chile presenta logros en desarrollo económico, con notables avances en pobreza. Sin embargo, persiste un alto nivel de desigualdad en el país.

El trabajo de [@cortes-orihuelaDecentralizingChileanMiracle2022] cuenta con datos de registros adminstrativos para realizar una estimación de movilidad intergeneracional a nivel de regiones en Chile. En particular usan registros del Programa de Seguro de Cesantía, entre los años 200 a 2018. Con esto se construye una muestra de niños con 28 a 33 años en 2018, vinculandolos con padres de 42 a 87 años en 2018. Esta muestra cuenta con 500 mil observaciones aproximadamente.

El ingreso permanente se construyó como un promedio mensual por 5 años. Los salarios fueron controlados por inflación (aunque no existe un índice de precios oficial que refleje la heterogeneidad de precios entre regiones, se han propuesto algunas metodologías a partir de variaciones en precio de viviendas, las cuales no se usan por posible sesgo en estimación del costo de vida por usar una canasta fija de bienes - la vivienda - [@lopezEstimacionInflacionRegional2012; @paredesMethodologyComputeRegional2011])

La asignación a la región de residencia se realiza a partir de la residencia de los niños a los 17 o 18 años por registros del Ministerio de Educación (para cuarto medio). El vínculo entre padres e hijos se realiza mediante los Certificados de Nacimiento del Registro Civil, que permiten vincular el rut de padres e hijos.

## Resultados para las Regiones de Chile

Este trabajo encuentra que la región con menor movilidad intergeneracional es la Araucanía, con marcado caracter agrícola, además de contar con la mayor tasa de pobreza del país (17%) y el mayor porcentaje de personas de etnia mapuche. Esta región solo contribuye solo con el 3% del PIB nacional. En contraste la región más movil es Antofagasta, con alta intesidad minera.

Estos resultados son interesantes, además por el rol del boom de los commodities en generar crecimiento inclusivo.


Los resultados de [@cortes-orihuelaDecentralizingChileanMiracle2022] indican una relación lineal entre ingresos de padres e hijos hasta el decil 9 para varias regiones. Esta no linealidad más pronunciada (mayor persistencia para ingresos más altos) a partir del decil 10 se aprecia en las regiones de Tarapacá, Coquimbo, Valparaíso, Metropolitana, Maule y Los Ríos.

En términos de movilidad, la región menos móvil es RM, con una correlación de rango de 0.25, siendo Arica y Parinacota la región con mayor independencia con 0.118. En términos de intervalos de confianza, RM no se distingue de O'Higgins, y Arica no se distingue de Aysén, Atacama, Antofagasta y Los Ríos.

Existe considerable heterogeneidad entre regiones. La mayor probabilidad de alcanzar el primer quintil partiendo desde el quintil más bajo, se encuentra en Antofagasta (29.8%), mientras que esta probabilidad baja a 8.5% en la región de la Araucanía. Esta última presenta un considerable sobrelape con El Maule, Los Lagos y Aysén.

Las probabilida de circulo de pobreza (mantenerse en el primer quintil) es más baja en Antofagasta con 12.5% y más alta en Araucnia con un 32.6% (con sobrelape con O'Higgins, El Maule y Ñuble)

Estos resultados a partir de datos del mercado laboral privado en Chile muestra una movilidad no lineal, alta persistencia en deciles más altos, privilegios. Además de dinámicas diferentes para distintas regiones. Es así que algunas regiones pueden considerarse “milagros económicos” mientras otras exhiben altos niveles de transmisión intergeneracional de privilegios y desventajas. Se encuentra mayor movilidad hacia arriba en regiones mineras y menor movilidad hacia arriba en regiones dedicadas a la agricultura.

Los autores reflexionan el rol de la política pública, siendo Chile un estado unitario en un territorio heterogeneo, indicando que es necesario mayor calidad de administración local que permita mejorar la progresividad de la inversión en capital humano y su productividad. Por otro lado, los resultados apuntan al rol del boom de los commodities en generar movilidad social, algo que se repite en el análisis regional en Estados Unidos y Canadá [@connollyIntergenerationalMobilityCanada2019].

### Comunas y Plebiscito

Una publicación más reciente de este trabajo incorpora estimaciones a nivel comunal y analisa su relación los resultados de votación del plebicito constitucional de entrada [@cortesorihuelaIntergenerationalEarningsPersistence2023]. Esto con el objetivo de revisar la relación entre la persistencia de ingresos y las preferencias por políticas redistributivas.
El modelo propuesto para vincular ambas, toma en consideración la literatura que indica que la perspectiva pesimista de movilidad social se vincula a mayor apoyo a politicas redistributivas, pero considerando que el mecanismo para asegurar bienestar para hijos puede ser por bienes públicos o transferencias de recursos de padres a hijos. Siendo ambas sustitas y siendo los bienes públicos finalmente pagados vía impuestos. En este contexto, los resultados muestran que las comunas con mayor persistencia de ingresos intergeneracionales hubo mayor porcentaje de votos en contra para modificar la constitución, indicando menor preferencias por políticas redistributivas.

## Otros resultados en el Mundo

Las investigaciones que analizan la variabilidad territorial de la movilidad intergeneracional en el mundo muestran resultados mixtos, con países con indices homogéneos (Suecia ) y otros con notable heterogeneidad (USA, Canadá, Australia).

En particular [@chettyOpportunityAtlasMapping2018; @chettyWhereLandOpportunity2014] analiza el caso de Estados Unidos, usando zonas de transporte, encontrando notables variaciones en "tierras de oportunidad" y "círculos de pobreza". Sus resultados indican que áreas de alta movilidad se correlacionan con una menor segregación residencial, menor desigualdad de ingresos, mejores escuelas primarias, capital social más significativo y mayor estabilidad familiar. Aunque estas correlaciones no indican los mecanismos causales que determinan la moviliadd hacia arriba.

El trabajo de [@connollyIntergenerationalMobilityCanada2019] calcula movilidad a nivel regional para USA y Canadá, mostrando que Canadá exhive mayor movilidad, en ciudades que experimentaron mercados laborales robustos debido al boom del petróleo, potash y otros precios de commodities. 

Europa - Italia, Dinamarca, Suecia

## Conclusión y Desarrollos Futuros

Notable heterogeneidad en Chile
Territorio heterogeneo
Expectativas de movilidad y relación con cultura, historia e instituciones
Vínculo como "imaginarios territoriales"

Necesidad de mejorar gestión local para accionar estrategias locales de desarrollo


Relaciones causales y caracterización (influencia segregación por ejemplo)

Relación entre movilidad, oportunidades, y expectativas e imaginarios territoriales.