# Productividad Local

En general se considera que la productividad está relacionada con la capacidad de las economías de generar bienes y servicios, y con estos mayor bienestar. Esta se define burdamente como la capacidad de transformar factores productivos en bienes y servicios, y es mayor cuando se puede produce más con relativamente los mismos factores. Es así que la adopción tecnológica o la innovación son centrales para estos análisis.

La literatura examina una serie de determinantes desde perspectivas individuales de empresas o agregadas a nivel de sectores productivos. Adicional a estas es necesario considerar factores territoriales y la expresion de los determinantes en el territorio, a raiz de las crecientes disparidades subnacionales y los patrones de disminución de crecimiento de la productividad.

El siguiente análisis se basa en el documento del laboratorio de la OCDE para la productividad territorial [@/content/paper/ba5edb47-en]

## Determinantes Productividad

Existen variados estudios sobre los determinantes de la productividad a nivel agregado, de industria y de firmas. Estos se mencionan a continuación, dando un enfoque local siguiendo el trabajo de [@/content/paper/ba5edb47-en]

### Tecnologia e Investigacion y Desarrollo

La innovación es un prerequistio para la actividad productivida al generar la tencologia necesario. Con las tecnologias de información el progreso tecnologico se ha vuelto un motor importante para el crecimiento de la prodictividad. Las actividades de investigacion y desarrollo aumentan la innovacion para tambien contribuyen a generar mayor capacidad de absorcion de firmas e industrias y por tanto tener mayores beneficios de las actividades innovativas.

A nivel territorial, se consdiera que la proximidad geografica es importante para el intercambio de conocimiento, en hubs de conocimiento. Esto se manifiesta en distintos canales, como la presencia de universidades de investigacion, laboratorios, industrias intensivas en investigacion, capital humano altamente educado, infraestructura de soporte de investigación como capital semilla, capital de riesgo, redes formale se informales y otros. Esto puede formar un sistema regional de innovacion. 

Es relevante tambien aumentar la capacidad de absorcion de conocmimento de la las empresas. Ya que la dimension espacial se manifiesta en los patrones de adopcion y efectos en productividad de los avances tecnologicos.

### Difusión de Conocimiento

Luego de que una tecnologia es creada, es necearia su difusión y absorción para que genere mejoras en productividad. La difusión de conocimiento se vuelve central en un mundo globalizado con empresas multinacionales, inversion extrangera directa y cadenas de valor globales. Además de afectar los resultados de sus empresas, la inversion extranjera directa y las empresas multinacionales pueden aumentar la productividad de las empresas domesticas en empreas relacionados mediante externalidades.

A nivel subnacional, las dinamicas locales se muestran importantes para la difusion de conocimiento. Los activos locales afectan las decisiones de ubicacion de las empreas multinacionales, como cadenas de valor que se centran en cluster de produccion reginoales. Activos intangibles regionales como capital humano, redes locales y masa critica de actores innovadores puden ser recursos centrales y ventajas para empresas multinacionales. Es así como las universidades muchas veces facilitan la difusion de conocimiento entre empresas.

### Emprendimiento y Rotacion de Empresas

La innovación además de aumentar la productividad de las empresas innovadoras, intensifica la competencia, que fuerza a las empresas incumbentes a aumentar su eficiencia, facilitando la reasignación de recursos a negocios más eficientes. En línea con el argumento de destrucción creativa, las empresas innovadoras reemplazan las menos innovadoras. Es así que existen modelos donde la entrada y salida de mercado de empresas puede mejorar la productividad. La entradade empresas mejora la productividad por distintos canales: startups implementan nuevas tecnologias, además de generar presión competitiva a mejorar eficiencia. Por otro lado existe literatura que estudia los efectos del comercio internacional en la productividad.

En su dimensión espacial, además de incorporar las tasas de startups y salida de empresas, se considera el concepto de Ecosistemas de Emprendimiento (EE) definidos como una serie de actores empresariales, organizaciones e instituciones interconectadas quecoalecen formal e informalmente para mediar y gobernar el desempeño del entorno de emprendimiento local. Este enfoque de vinculos es escencialmente determinado geograficamente. Siendo precondición de éxito de conceptos como cluster industriales, sistemas de innovación y economía del conocimiento. Dentro de este enfoque la presencia de universidades y centros de investigación y oficinas de transferencia tecnológica juegan un rol central. Además del capital humano regional, que incluye además de educación el conocimiento de administración, la cultura de aceptación del fracaso y reciclado del emprendimiento.

### Capital Humano

El vinculo de capital humano y productividad se manifiesta al menos en tres canales: habilidades empresariales (manejo de empresa, eleccion de tecnologia, asignacion de recursos), nivel de capital humano (fuerza de trabajo mas educada) y calidad del capital humano (mayor innovación). 

En su dimensión espacial, se destaca la heterogeneidad de la calidad del capital humano en el espacio subnacional. Además del debate respecto de si los trabajo siguen a las personas o las personas siguen los trabajos. Esta migración interna se acentúa para trabajadores altamente calificados, los cuales son más probables de elegir dónde vivir. Es así que existe una concentración en zonas urbanas, donde existan suficientes equipamientos y servicios, en una co-localción de trabajos y servicios de alta calidad.

### Perfiles y tendencias demográficas

Existe un debate sobre la composición etárea de la fuerza de trabajo y su impacto en productividad. Esto porque se puede esperar un deterioro de productividad al aumentar la edad y disminuir la fuerza fisica o deteriorarse la salud, lo cual puede ser contratado por experiencia acumulada y habilidad mental. 

Asi mismo es relevante la tasa de dependencia, que es el porcentaje de población que no trabaja a la población en edad de trabajar. Esta se considera en general con efecto negativo en productividad. Sin embargo, con los ultimos avances tecnologicos, paises con baja tasa de crecimiento de la fuerza laboral estarían más presionados a adoptar tecnologías más eficientes en recursos laborales y de automatización.

Siendo que los perfiles demográficos y etáreos difieren sustantivamente dentro de los páises, sobre todo entre las áreas rurales y urbanas, se encuentra que la laiteratura a nivel regional no ha logrado considerar el rol mitigador de productividad de la estructura etarea. Principalmente por foco solo en un país, y encontrando resultados contradictorios. Una perspectiva regional internacional reciente para países OCDE encuentra que el crecimiento de productividad regional no es suficiente en varias regiones para superar el efecto de la estructura etarea.

### Finanzas

Los sistemas financieros se vinculan al crecimiento económico mediante cinco canales: 

- Producen informacion sobre posibles inversiones y asignación de recursos

- Monitorean inversiones y ejercen control corporativo

- Facilitan el manejo, diversificacion e intercambio de riesgo

- Mobilizan y consolidan ahorros

- Facilitan el intercambio de bienes y servicios.

Además existen mecanismos indirectos por los cuales influencian el desempeño productivo, estos se relacionan a los dinámicas económicas, innovatividad de empresas y acumulación de capital físico y humano.

Cuando funcionan bien, los sistemas financieros permiten acceso a crédito a start ups prometedores, dando recursos para inversión en I+D, capital y trabajo. Es así que las políticas que aseguran un sistema financiero eficiente son precondición para una vínculo positivo entre productividad y finanzas.

Desde una perspectiva territorial, reconociendo que la falta de financiamiento puede ser un impedimento al crecimiento, se encuentra que el acceso a finanzas es especifico del lugar. Es así que las oportunidades de inversión se aglomeran de forma desproporcionada en grandes ciudades, potencialmente perjudicando el desempeño de compañias en regiones menos centrales. Sin embargo la evidencia de beneficios por cercania a finanzas no es conclusiva, encontrando efectos positivos o ningun efecto. Aun asi el acceso dependiente del espacio puede afectar otros indicadores económicos relevantes para el desepeño productivo.

### Instituciones, Regulacion y Politicas

El efecto sobre productividad de Instituciones, Regulación y Políticas se manifiesta de forma indirecta al influenciar el resto de determinates ya mencionados. Esto porque las institcuiones definen el "espacio" donde se juega, formando una estructura de incentivos. Es por esto que una relación causal es dificil de establecer, ya que es un conjunto de instituciones disimiles las que definen la estructura, llamado tambien infaestructura social. Sin embargo, la protección de derechos de propiedad es particularmente relevante.

Aunque las políticas aplicadas sean ciegas al espacio, su impacto no necesarimente es neutral en el espacio. Esta dimensión espacial de las instituciones se refuerza por las caracteristicas regionales. La distancia de las regiones de la frontera productiva incluencia qué regiones son más responsibas a políticas estructurales. Así mismo, regiones remotas son más afectadas por políticas que impiden emprendimiento, o políticas laborales tienen efectos desiguales en regiones urbanas y aglomeradas comparado a areas rurales dispersas. El mix de composición de industrias regional también afectará ya que ciertas industrias son más responsivas a las políticas, debiendo considerarse el mix de empresas grandes y pequeñas en la región. Por último, las politicas pueden diferir en su implementación en el espacio, ya que la calidad del gobierno local puede variar sustantivamente dentro de cada región.

## Determinantes Espaciales

La literatura de ciencia regional examina en detalle los factores directamente relacionado al espacio, a continuación se revisan algunos de estos elementos.

### Geografia y Fronteras

El efecto del territorio en sus formas y disponibilidad de cursos de agua historicamente ha dado forma a oportunidades económicas. Las cuales, luego a través del legado de la composición industrial generada, continua impactando el comportamiento humano y los resultados socioeconómicos. Es así que areas más "rugosas" con caracteristicas protectoras del ambiente pueden generar fragmentación política en la forma de bordes y nacionaes. Los bordes afectan el espacio socio-económico y sus procesos, al aumentar los costos de transacción. Esta discontinuidad del espacio se vincula con diferentes marcos legales además de diferencias culturales y de lenguaje entre otras. La cercanía a los bordes también genera comunmente regiones que se desempeñan peor debido a la discontinuidad espacial y la distancia de los mercados centrales del país.

### Economias de Aglomeracion

El vínculo entre aglomeraciones urbanas y productividad está bien documentado teórica y empíricamente. Estas economías de aglomeración ocurren cuando las personas y empresas se co-ubican. Las fuentes de estas economias son las externalidades tecnologicas, la aglomeración de trabajadores y vinculos de input intermedios, que implican compartir, coincidir y aprender.

El efecto se compone de algomeracion pura (trabajadores y empresas se hacen más productivos en ciudades) y un efecto de seleción (inicialmente los trabajadores y firmas más productivas se ubican en las ciudades). Los mecanismos incluyen un mejor match entre trabajadores y empresas, el aprender haciendo en la ciudad, existiendo un efecto de aprendizaje por estar situado en areas urbanas más grandes. Por otro lado, empresas ubicadas en proximidas son más probables de aprender de otras y adoptar estrategias exitosas de sus vecinos.

Estas dinámicas pueden levantar los resultados económicos de las areas colindantes, si estan bien conectadas, enlos llamados "hinterlands". Estos efectros se han llamado efectos de difusión de aglomeración (Aglomeration Spread Effects). El motor de esto son la demanda urbana de bienes, servicios y equipamientos rurales y por el acceso rural a los mercados urbanos. Con esto las ciudades pequeñas y las areas rurales alrededor de ciudades más grandes pueden acceder a los beneficios de las economias de aglomeracion sin estar en una aglomeración, mediante este "tamaño prestado". Sin embargo, si la conectividad es mala, la congestión impide a los residentes urbanos vivir y gastar en areas rurales y cortando los emprendimientos rurales de los mercados urbanos. 

### Infraestructura tradicional y digital

La inversión en infraestructura es un componente común de la política de desarrollo regional. Estos objetos de infraestructura, como carreteras, aeropuertos, redes de comunicación y redes eléctricas, facilitan el acceso a nuevos recursos y aumental la productividad de los existentes. Además son bienes no exclusivos, por lo que generan externalidades positivias, fortalecioendo las externalidades de aglomeración. La cuantificación de su efecto, sin embargo, es una tarea dificil. 

El impacto se puede apreciar mediante la reducción de costos de transpoerte, que aumentan la productividad de empresas locales. Además su impacto va más allá de los lugares donde se realizan, afectando regiones periféricas. Aunque pueden generar un efecto de desplazamiento en estas regiones.

Al facilitar el movimiento de personas, afectan las decisiones de ubicación de las empresas. La proximidad de aeropuertos es importante. Al inducir concentracióin de persronas y empresas pueden influenciar la distribución de la actividad económica en el espacio.

Las telecomunicaciones, por otro lado, reducien costos de comunicación y permiten expansión de mercados e intercambio de información. El internet permite también acceso a mercados globales con consumidores potenciales y proveedores, además de minimizar costos de transacción al impactar operaciones de administración como el contacto con clientes.

### Gobernaza, provision de bienes publicos

Las economías de aglomeración implican también un conjunto de desafíos que es necesario gestionar, tales como contaminación, congestión, salubridad pública y sanitización. La estrctura urbana de gobernanza usalmente difiere en su nivel de fragmentación. Mayor fragmentación podría mejorar la calidad de provisión de bienes públicos por competencia, sin embargo también aumenta los costos de coordinación. Por ejemplo, las areas funcionales urbanas (definidas por patrones de actividad economica) usualmente no coinciden con los bordes administrativos. Esta discordancia espacial pueden empeorar los resultados económicos al añadir burocracias, congestión y disminuyendo el atractivo regional para los trabajadores altamente calificados.

Incluso existe la posibilidad de que las unidades de gobierno local no logren reconocer las externalidades positivas que ocurren a nivel de area funcional. Esto afectaría tambien el bienestar mediante sistemas de transporte ineficientes, falta de remosión de basura, mayor contaminación y otras fallas de coordinación. Estos efectos también dependerían de las funciones de gobierno y el continuo urbano rural.