# Resumen

En el estudio de la pobreza podemos encontrar diversos enfoques que la describen desde elementos de recursos monetarios hasta incorporar las diversas dimensiones de carencias que están asociadas, considerando acceso a oportunidades y elementos subjetivos. Estos elementos se identifican más clarramente en los apartados de pobreza monetaria y pobreza multidimensional.

Estos enfoques consideran evaluar mediante encuestas a hogares las carencias de los hogares, considerando el ingreso disponible, las lineas de pobreza derivadas a partir del análisis de la canasta básica de consumo, y también elementos de educación, salud, trabajo, vivienda y redes bajo la pobreza multidimensional. 

El análisis de la pobreza implica un componente normativo al decidir qué indicadores medir, y también el umbral bajo el cual se considera la situación de pobreza. En Chile, el estudio del fenomeno y las actualizaciones metodológicas involucran a diversas instituciones como el Ministerio de Desarrollo Social, el Instituto Nacional de Estadísticas, la CEPAL, diversas comisiones de expertos y la asesoria de organizaciones internacionales. Todas estas han desarrollado un trabajo que busca asegurar la mayor robustez técnica de la medición del fenómeno. 

A pesar de la completitud que buscan alcanzar estos indicadores existen enfoques complementarios que permiten ampliar además las formas de analizar cómo se expresa la pobreza. Siendo estas derivadas de las llamadas Dimensiones Faltantes que relevan un elemento más subjetivo, relacionado a la agencia, y la no humillación, o la pobreza Energética, que se enfoca en elementos relacionados al acceso a fuentes de energía confiables y de calidad, elemento clave para el desarrollo de las personas en la sociedad.

El estudio de la pobreza está muy relacionado también con el estudio del bienestar. Los ámbitos muchas veces se repiten, siendo una diferencia que el enfoque de bienestar no requiere definir umbrales de carencia. 

Desde un punto de vista territorial, se incluye también el análisis de la pobreza rural. La cual considera un conjunto de elementos que permiten iniciar el análisis más relacionado con las causas. En este sentido, se puede considerar como los distintos territorios entregan oportunidades de desarrollo a quienes los habitan. Un enfoque interesante es el de la Movilidad Intergeneracional, la cual estudia como los ingresos de los padres influyen en las oportunidades e ingresos de sus hijos. Estudios recientes en Chile muestran como difieren por region y comuna estas oportunidades. Estos se relacionan a estudios que buscan desagregar territorialmente el "milagro chileno", encontrando que los beneficios del desarrollo no se distribuyen uniformemente en el territorio. 

Para complementar estos enfoques, se revisa la literatura relacionada a los determinantes de la productividad territorial. Esto es relevante ya que en general territorios más productivos tienen mayor capacidad de generar y distribuir bienestar. Con esta visión se puede "cerrar" la panorámica de los elementos necesarios para generar un diagnóstico territorial que permita comprender el fenómeno de la pobreza. Queda como desafío profundizar en las interrelaciones de sus expresiones y sus causas.

## Indicadores

Entre las dimensiones e indicadores encontrados se pueden contar los siguientes:

- Pobreza Monetaria: nivel de ingreso de los hogares

- Pobreza Multidimensional
    - Educacion
        - Asistencia
        - Rezago Escolar
        - Escolaridad
    - Salud
        - Malnutrición de Niños y Niñas
        - Adscripción al Sistema de Salud
        - Atención
    - Trabajo y Seguridad Social
        - Ocupación
        - Seguridad Social
        - Jubilación
    - Vivienda y Entorno
        - Habitabilidad
        - Servicios Básicos
        - Entorno
    - Redes y Cohesión Social
        - Apoyo y participación social
        - Trato Igualitario
        - Seguridad
- Dimensiones Faltantes
    -Empoderamiento y Agencia
    - Seguridad Física
    - Capacidad de ir por la vida sin sentir vergüenza
    - Calidad del empleo
    - Conectividad Social
    - Bienestar psicológico y subjetivo
- Pobreza Energética
    - Gasto excesivo en energías
    - Vulnerabilidad y riesgo climático
    - Acceso a electricidad
    - Calefacción con fuente contaminante
- Pobreza Rural
    - Falta de Infraestructura
    - Barreras Geográficas
    - Acceso Insuficiente a Mercados
    - Servicios sociales y educacionales inadecuados
- Productividad
    - Tecnología e Investigación y Desarrollo
    - Difusión de Conocimiento
    - Emprendimiento y Rotación de Empresas
    - Capital Humano
    - Finanzas
    - Instituciones
    - Regulación y Políticas
    - Perfiles y tendencias Demográficas
    - Geografía y Fronteras
    - Economías de Aglomeración
    - Infraestructura
    - Gobernanza. Provisión de Bienes Públicos